// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/cmd/api/server"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/configs"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers"
	academic_term3 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/academic_term"
	admin2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/admin"
	auth3 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/auth"
	award3 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/award"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/dev"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/organization"
	request3 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/request"
	user3 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/handlers/user"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/infrastructure/auth"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/infrastructure/database"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/infrastructure/oauth"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/middlewares"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/academic_term"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/award"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/campus"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/department"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/faculty"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/request"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/repositories/user"
	academic_term2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/academic_term"
	"github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/admin"
	auth2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/auth"
	award2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/award"
	campus2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/campus"
	department2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/department"
	faculty2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/faculty"
	request2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/request"
	user2 "github.com/472-68-AgileDevOps/p2-final-project-backend-team/internal/services/user"
)

// Injectors from wire.go:

func InitializeAPI() (*server.EchoServer, error) {
	config := configs.NewConfig()
	db := database.NewPostgrest(config)
	repository := user.NewUserRepository(db)
	campusRepository := campus.NewCampusRepository(db)
	service := campus2.NewCampusService(campusRepository)
	facultyRepository := faculty.NewFacultyRepository(db)
	facultyService := faculty2.NewFacultyService(facultyRepository)
	departmentRepository := department.NewDepartmentRepository(db)
	departmentService := department2.NewDepartmentService(departmentRepository)
	adminService := admin.NewAdminService(repository, service, facultyService, departmentService)
	adminHandler := admin2.NewAdminHandler(adminService)
	provider := oauth.NewGoogleProvider(config)
	tokenManager := auth.NewJWTManager(config)
	authService := auth2.NewAuthService(provider, repository, tokenManager)
	authHandler := auth3.NewAuthHandler(authService, config)
	userService := user2.NewUserService(repository, service, facultyService, departmentService, tokenManager)
	handler := user3.NewUserHandler(userService)
	awardRepository := award.NewRepository(db)
	requestRepository := request.NewRepository(db)
	awardService := award2.NewService(awardRepository, requestRepository)
	awardHandler := award3.NewHandler(awardService)
	academic_termRepository := academic_term.NewAcademicTermRepository(db)
	storageClient, err := ProvideMinioClient(config)
	if err != nil {
		return nil, err
	}
	requestService := request2.NewService(requestRepository, repository, academic_termRepository, storageClient)
	requestHandler := request3.NewHandler(requestService, storageClient)
	devHandler := dev.NewDevHandler(config, tokenManager, repository)
	organizationHandler := organization.NewOrganizationHandler(service, facultyService, departmentService)
	academic_termService := academic_term2.NewAcademicTermService(academic_termRepository)
	academicTermHandler := academic_term3.NewHandler(academic_termService)
	handlersHandler := handlers.NewHandlers(adminHandler, authHandler, handler, awardHandler, requestHandler, devHandler, organizationHandler, academicTermHandler)
	authMiddleware := middlewares.NewAuthMiddleware(config)
	rbacMiddleware := middlewares.NewRBACMiddleware()
	echoServer := server.NewEchoServer(config, handlersHandler, authMiddleware, rbacMiddleware)
	return echoServer, nil
}
